language: node_js
node_js:
  - node

services: mongodb

install:
  - npm install
  - node bin/www &
  - wget https://github.com/matryer/silk/releases/download/0.5.1/silk-0.5.1-linux-amd64.zip
  - unzip silk-0.5.1-linux-amd64.zip

script:
  - silk-0.5.1-linux-amd64/silk -silk.url="localhost:3000" api_docs.md
