language: node_js
node_js:
  - node

services: mongodb

install:
  - npm install
  - node bin/www debug &
  - wget https://github.com/matryer/silk/releases/download/0.5.1/silk-0.5.1-linux-amd64.zip
  - unzip silk-0.5.1-linux-amd64.zip
  - sleep 2 # give node a little more time to start

script:
  - silk-0.5.1-linux-amd64/silk -silk.url="http://localhost:3000" api_docs.md
